<?php


use Ehua\Caiji\Selenum;
use Ehua\Tool\Tool;
use Facebook\WebDriver\Exception\WebDriverException;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverSelect;
use JonnyW\PhantomJs\Client;

require_once "vendor/autoload.php";
require_once "config.php";

class Temp
{
    /**
     * 入口
     */
    function init()
    {

        $this->ips = $this->getip(10);

        $temp = file_get_contents(getcwd() . '\config\tiezi.txt');
        $temp = explode("\r\n", $temp);
        $arr = [];
        $temp = array_filter($temp);
        foreach ($temp as $k => $dat) {
            $da = explode("----", $dat);
            $arr[] = $da;
        }

        foreach ($arr as $dat) {
//            $max = count($this->config['auth']);
            $thread_id = $dat[0];
            $post_id = $dat[1];
            for ($i = 0; $i < $dat[2]; $i++) {
                $this->loop($i, $thread_id, $post_id);
            }
        }

    }

    /**
     * 获取代理IP
     * @param $num
     * @return false|string[]
     */
    public function getip($num)
    {
        // Generated by ApiPost: https://www.apipost.cn/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'http://demo1.ehua.pro/api/index/getip?num=' . $num);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = 'User-Agent: Apipost client Runtime/+https://www.apipost.cn/';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        $result = explode(' ', $result);
        return $result;
    }

    /**
     * 逻辑循环
     * @param $i
     * @param $thread_id
     * @param $post_id
     */
    public function loop($i, $thread_id, $post_id)
    {
        $this->i = $i;
        $info = $this->config['auth'][$this->i];
//        $thread_id = '7939728486';//帖子ID
//        $post_id = '144847264609';//评论者ID

        //获取列表数据
        $url = "https://tieba.baidu.com/mg/p/getPbData?kz=$thread_id&obj_param2=chrome&format=json&eqid=&refer=wappass.baidu.com&frwh=index&traceid=&uid=1658660790307_213&pn=1&rn=1";
        $baiduData = $this->getData($url, $info[2]);
		var_dump($baiduData);
        $baiduData = json_decode($baiduData, true);
        if ($baiduData[['errno'] != 0]) {
            die('baidu error:' . $baiduData['errmsg']);
        }

        //执行点赞
        $tbs = $baiduData['data']['tbs'];
        var_dump($tbs);
        $forum_id = $baiduData['data']['forum']['id'];
        var_dump($forum_id);
//        $post_id = $baiduData['data']['post_list'][1]['id'];//todo $post_id 动态调整

        $param = [
            'forum_id' => $forum_id,
            'post_id' => $post_id,
            'tbs' => $tbs,
            'thread_id' => $thread_id,
        ];
        $url = 'http://demo1.ehua.pro/api?' . http_build_query($param);
//        $this->driver->get($url);
//        $r = $this->driver->findElement(WebDriverBy::id('sign'))->getText();
        var_dump($url);
        $r = $this->phantomjs($url);

        preg_match("/3135491919.*?3135491919/", $r, $a);
        if (!isset($a[0])) {
            die('sign error');
        }
        $sign = str_replace('3135491919', '', $a[0]);
		var_dump($sign);
        $param = [
            'forum_id' => $forum_id,
            'thread_id' => $thread_id,
            'post_id' => $post_id,
            'op_type' => 0,
            'agree_type' => 2,
            'obj_type' => 1,
            'tbs' => $tbs,
            'fr' => 'newwise',
            'sign' => $sign,
        ];
        $rr = $this->baiduPost($param, $info[2]);
        var_dump($rr);
    }

    /**
     * 初始化
     * Temp constructor.
     */
    public function __construct()
    {
        $this->i = 5;
        $this->config = get_config();
//        $this->driver = Selenum::init(false, __DIR__ . '\lib\Chrome-bin\chrome.exe');
//        $this->driver = Selenum::Session_init('895ea7b9b5dc4759faad0fe042e7632f');
        $temp = file_get_contents(getcwd() . '\config\account.txt');
        $temp = explode("\r\n", $temp);
        foreach ($temp as $dat) {
            $da = explode("----", $dat);
            $arr[] = $da;
        }
        $this->config['auth'] = $arr;
//        var_dump($this->driver->getSessionID());

        if(file_get_contents(getcwd().'\config\daili.cfg')==1){
            $this->config['agency'] = true;
        }else{
            $this->config['agency'] = false;
        }

    }

    /**
     * 获取sign
     * @param $url
     * @return bool|string
     */
    public function phantomjs($url)
    {

        $client = Client::getInstance();
        $client->getEngine()->setPath(getcwd() . '\bin\phantomjs.exe');
        /**
         * @see JonnyW\PhantomJs\Http\Request
         **/
        $request = $client->getMessageFactory()->createRequest($url, 'GET');

        /**
         * @see JonnyW\PhantomJs\Http\Response
         **/
        $response = $client->getMessageFactory()->createResponse();

        // Send the request
        $client->send($request, $response);

        if ($response->getStatus() === 200) {

            // Dump the requested page content
            return $response->getContent();
        } else {
            return false;
        }

    }

    /**
     * 获取当前贴吧信息
     * @param $url
     * @param $cookie
     * @return bool|string
     */
    function getData($url, $cookie)
    {
        // Generated by ApiPost: https://www.apipost.cn/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Language: zh-CN,zh;q=0.9';
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Referer: https://tieba.baidu.com/p/7939728486?frwh=index&traceid=&uid=1658660790307_213';
        $headers[] = 'Referer-Asyn: https://wappass.baidu.com/';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Sec-Ch-Ua: \".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
        $headers[] = 'Sec-Ch-Ua-Platform: \"Android\"';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'Cookie: ' . $cookie;


        if ($this->config['agency']) {
            $ipa = $this->ips[rand(0, count($this->ips) - 1)];
            $ipa = @array_map('trim', $ipa);
            $ip = explode(':', $ipa)[0];
            $prot = explode(':', $ipa)[1];
            curl_setopt($ch, CURLOPT_PROXYAUTH, CURLAUTH_BASIC); //代理认证模式
            curl_setopt($ch, CURLOPT_PROXY, $ip); //代理服务器地址
            curl_setopt($ch, CURLOPT_PROXYPORT, $prot); //代理服务器端口
            curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); //使用http代理模式
        }


        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, '0');

        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, '0');
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }

    /**
     * 执行点赞
     * @param $param
     * @param $cookie
     * @return bool|string
     */
    public function baiduPost($param, $cookie)
    {
        // Generated by ApiPost: https://www.apipost.cn/
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://tieba.baidu.com/mg/o/submit/opAgree?' . http_build_query($param));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);

        $headers = array();
        $headers[] = 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'Accept-Language: zh-CN,zh;q=0.9';
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Content-Length: 0';
        $headers[] = 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8';
        $headers[] = 'Origin: https://tieba.baidu.com';
        $headers[] = 'Referer: https://tieba.baidu.com/p/7939728486?frwh=index&traceid=&uid=1658660790307_213';
        $headers[] = 'Referer-Asyn: https://wappass.baidu.com/';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Sec-Ch-Ua: \".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"';
        $headers[] = 'Sec-Ch-Ua-Mobile: ?1';
        $headers[] = 'Sec-Ch-Ua-Platform: \"Android\"';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'Cookie: ' . $cookie;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, '0');

        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, '0');

        if ($this->config['agency']) {
            $ipa = $this->ips[rand(0, count($this->ips) - 1)];
            $ipa = @array_map('trim', $ipa);
            $ip = explode(':', $ipa)[0];
            $prot = explode(':', $ipa)[1];
            curl_setopt($ch, CURLOPT_PROXYAUTH, CURLAUTH_BASIC); //代理认证模式
            curl_setopt($ch, CURLOPT_PROXY, $ip); //代理服务器地址
            curl_setopt($ch, CURLOPT_PROXYPORT, $prot); //代理服务器端口
            curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); //使用http代理模式
        }


        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;
    }
}

$A = new Temp();
$A->init();